### ISSUE TITLE
Pages Directory renamed.

### ISSUE THREAD

**Issue by ghost** [hibbitts-design/grav-skeleton-open-publishing-space#3]
Paul I just installed the latest update and my pages directory was renamed again. Maybe the format rings a bell? Its renamed to "pages.10-20-2018-23-59-04" I am now on  Quark Open Publishing v1.2.9
The pages directory in the themes _demo directory is untouched.

**Comment by paulhibbitts** [comment]
Hi @roelfrenkema , thanks for posting your issue here. When you are referring to your page directory being renamed do you mean in your main 'user' folder? This should never be happening with a theme update, and I have not seen this issue before.

I did update the demo pages, and usually the behavior is that only the affected files are changed in the theme _demo folder are updated. What OS are you running? Do you have any programs running in the background which may be doing some sort of backup or file monitoring? Did you perhaps at one point make a symbolic link to the pages in the theme _demo folder to your main user folder? Sorry for all the questions, just trying to get an idea of what might be going on.

**Comment by ghost** [comment]
I am running Ubuntu 18.04 and there are no links, not symbolic or hardlinks. Its updating the themefiles fine just the pages not. 
I really dont see why the pages directory is renamed in the first place or is the3 ment for those in the demo dir. I did make extensive changes as far as user templates is concerned but that should not be an issue.

**Comment by paulhibbitts** [comment]
Thanks for the info @roelfrenkema , I am sorry that you have been having issues with the theme updates.

I am not sure what is causing this issue, it has not been reported before and I have not seen it myself. There must be something causing this issue though, is there anything in your Grav log file (/logs/grav.log)? Could you install the skeleton on another machine and see if a future update has the same issue there? Oh, I should have asked is this a local install or on a Webserver?

**Comment by ghost** [comment]
Well actually its a local webserver. I live in the Netherlands and we are allowed to run our own servers on our internetconnections. htts://www.roelfrenkema.com 

And I do have some issues in the log indeed:

```
[2018-10-21 04:51:33] grav.CRITICAL: Undefined index: HTTP_HOST - Trace: #0 /home/roelfrenkema/public_html/system/src/Grav/Common/Debugger.php(314): Whoops\Run->handleError(8, 'Undefined index...', '/home/roelfrenk...', 48) #1 /home/roelfrenkema/public_html/system/src/Grav/Common/Service/PageServiceProvider.php(48): Grav\Common\Debugger->deprecatedErrorHandler(8, 'Undefined index...', '/home/roelfrenk...', 48, Array) #2 /home/roelfrenkema/public_html/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\PageServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #3 /home/roelfrenkema/public_html/user/plugins/simplesearch/simplesearch.php(84): Pimple\Container->offsetGet('page') #4 /home/roelfrenkema/public_html/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Grav\Plugin\SimplesearchPlugin->onPagesInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #5 /home/roelfrenkema/public_html/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #6 /home/roelfrenkema/public_html/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #7 /home/roelfrenkema/public_html/system/src/Grav/Common/Grav.php(279): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #8 /home/roelfrenkema/public_html/system/src/Grav/Common/Processors/PagesProcessor.php(25): Grav\Common\Grav->fireEvent('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #9 /home/roelfrenkema/public_html/system/src/Grav/Common/Grav.php(131): Grav\Common\Processors\PagesProcessor->process() #10 /home/roelfrenkema/public_html/system/src/Grav/Common/Grav.php(370): Grav\Common\Grav->Grav\Common\{closure}() #11 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('pages', 'Pages', Object(Closure)) #12 /home/roelfrenkema/public_html/system/src/Grav/Common/Grav.php(346): call_user_func_array(Object(Closure), Array) #13 /home/roelfrenkema/public_html/system/src/Grav/Common/Grav.php(132): Grav\Common\Grav->__call('measureTime', Array) #14 /home/roelfrenkema/public_html/index.php(54): Grav\Common\Grav->process() #15 {main} [] []
[2018-10-21 08:04:29] grav.CRITICAL: Undefined index: HTTP_HOST - Trace: #0 /home/roelfrenkema/public_html/system/src/Grav/Common/Debugger.php(314): Whoops\Run->handleError(8, 'Undefined index...', '/home/roelfrenk...', 48) #1 /home/roelfrenkema/public_html/system/src/Grav/Common/Service/PageServiceProvider.php(48): Grav\Common\Debugger->deprecatedErrorHandler(8, 'Undefined index...', '/home/roelfrenk...', 48, Array) #2 /home/roelfrenkema/public_html/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\PageServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #3 /home/roelfrenkema/public_html/user/plugins/simplesearch/simplesearch.php(84): Pimple\Container->offsetGet('page') #4 /home/roelfrenkema/public_html/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Grav\Plugin\SimplesearchPlugin->onPagesInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #5 /home/roelfrenkema/public_html/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #6 /home/roelfrenkema/public_html/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #7 /home/roelfrenkema/public_html/system/src/Grav/Common/Grav.php(279): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #8 /home/roelfrenkema/public_html/system/src/Grav/Common/Processors/PagesProcessor.php(25): Grav\Common\Grav->fireEvent('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #9 /home/roelfrenkema/public_html/system/src/Grav/Common/Grav.php(131): Grav\Common\Processors\PagesProcessor->process() #10 /home/roelfrenkema/public_html/system/src/Grav/Common/Grav.php(370): Grav\Common\Grav->Grav\Common\{closure}() #11 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('pages', 'Pages', Object(Closure)) #12 /home/roelfrenkema/public_html/system/src/Grav/Common/Grav.php(346): call_user_func_array(Object(Closure), Array) #13 /home/roelfrenkema/public_html/system/src/Grav/Common/Grav.php(132): Grav\Common\Grav->__call('measureTime', Array) #14 /home/roelfrenkema/public_html/index.php(54): Grav\Common\Grav->process() #15 {main} [] []
[2018-10-21 23:56:12] grav.CRITICAL: Undefined index: HTTP_HOST - Trace: #0 /home/roelfrenkema/public_html/system/src/Grav/Common/Debugger.php(314): Whoops\Run->handleError(8, 'Undefined index...', '/home/roelfrenk...', 48) #1 /home/roelfrenkema/public_html/system/src/Grav/Common/Service/PageServiceProvider.php(48): Grav\Common\Debugger->deprecatedErrorHandler(8, 'Undefined index...', '/home/roelfrenk...', 48, Array) #2 /home/roelfrenkema/public_html/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\PageServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #3 /home/roelfrenkema/public_html/user/plugins/simplesearch/simplesearch.php(84): Pimple\Container->offsetGet('page') #4 /home/roelfrenkema/public_html/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Grav\Plugin\SimplesearchPlugin->onPagesInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #5 /home/roelfrenkema/public_html/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #6 /home/roelfrenkema/public_html/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #7 /home/roelfrenkema/public_html/system/src/Grav/Common/Grav.php(279): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #8 /home/roelfrenkema/public_html/system/src/Grav/Common/Processors/PagesProcessor.php(25): Grav\Common\Grav->fireEvent('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #9 /home/roelfrenkema/public_html/system/src/Grav/Common/Grav.php(131): Grav\Common\Processors\PagesProcessor->process() #10 /home/roelfrenkema/public_html/system/src/Grav/Common/Grav.php(370): Grav\Common\Grav->Grav\Common\{closure}() #11 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('pages', 'Pages', Object(Closure)) #12 /home/roelfrenkema/public_html/system/src/Grav/Common/Grav.php(346): call_user_func_array(Object(Closure), Array) #13 /home/roelfrenkema/public_html/system/src/Grav/Common/Grav.php(132): Grav\Common\Grav->__call('measureTime', Array) #14 /home/roelfrenkema/public_html/index.php(54): Grav\Common\Grav->process() #15 {main} [] []

```

**Comment by paulhibbitts** [comment]
Thanks @roelfrenkema, nothing stands out to me in the error log - perhaps empty that file and start with a fresh log for future events?

Are you working from an Open Publishing Space skeleton or working from another Grav package and then have installed Quark Open Publishing? 

As a test, I wonder if it might be worthwhile to install another one of my skeletons (Open Course Hub), and then see if the same behavior happens with a theme update? My skeletons are under very active development, so the demo pages are often updated.

Another possible option is for you to see if Quark alone might support your site and make that the active theme.

Sorry I cannot be more helpful at this point, I am still trying to think what may be causing the issue. To confirm, is your Page folder just being renamed (and the files within it remain)?

**Comment by OleVik** [comment]
A couple of things need clarifying:

1. How are you updating the theme? Using the Admin-interface, extracting a zip-file, or using the GPM directly?
2. Is it the /user/pages folder that is renamed, but the contents therein untouched?

**Comment by ghost** [comment]
At the moment only with GPM and only the /user/pages folder is renamed, the content is untouched. It does condition me to make plenty og backups though :-) I will try and experiment a little bit on another machine. As this is a production machine I dont want to fiddle there with the templates.

**Comment by paulhibbitts** [comment]
I am closing this issue - please reopen if you are still encountering the issue.

**Comment by paulhibbitts** [comment]
Hi @roelfrenkema , I've finally been able to track this issue down and update your original issue on the Grav repo https://github.com/getgrav/grav/issues/2225
